# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/Mi8937/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/ulysse-2

PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(LOCAL_PATH)/camera/ulysse/vendor/,$(TARGET_COPY_OUT_VENDOR)/)
